# -*- coding: utf-8 -*-
"""Categoria.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xN0a4UZZEMMBOe40ZLO6_gPh9xkI3GGz
"""

class Categoria:
    def __init__(self, nombre, descripcion):
        self.nombre = nombre
        self.descripcion = descripcion
        self.productos = []

    def agregar_producto(self, producto):
        self.productos.append(producto)

    def eliminar_producto(self, producto):
        self.productos.remove(producto)