# -*- coding: utf-8 -*-
"""Proveedor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozSOT2i-at-7LiQyWptY4_Kbgtwru3BB
"""

class Proveedor:
    def __init__(self, nombre, direccion, telefono):
        self.nombre = nombre
        self.direccion = direccion
        self.telefono = telefono
        self.productos_suministrados = []

    def agregar_producto(self, producto):
        self.productos_suministrados.append(producto)

    def eliminar_producto(self, producto):
        self.productos_suministrados.remove(producto)